### ISSUE TITLE
Intégration à HA

### ISSUE THREAD

**Issue by floriant29** [hacf-fr/freebox-api#150]
Bonjour,

J'ai quitté Jeedom (qui intégrait la gestion du pack de sécurité de la freebox delta ) pour HA. Mais le plugin natif freebox de HA n'intègre pas les éléments du pack sécurité.
Du coup je suis tombé sur freebox-api mais je n'arrive pas à comprendre le principe d'intégration de cette api à HA, malgré des recherches sur les forums.

Quelqu'un aurait des pistes ?

Merci !

**Comment by oncleben31** [comment]
Bonjour, 

Bienvenu tu n'es pas seul à à avoir fait cette transition. 
Donc cette lib n'est qu'une interface entre la freebox et Home Assistant. Elle est déjà intégrée dans le code de la dernière version de HA. En revanche l'intégration est récente et toutes les fonctionnalités de ce module Python ne sont pas encore utilisé dans HA.Je t'invite à en parler ici, ou sur le Forum / Discord de HACF.fr, car il n'y a pas vraiment grand chose à par paramétrer l'intégration avec ta freebox depuis le menu "intégration".

**Comment by floriant29** [comment]
Merci pour ces explications !
Je viens de trouver une demande d'uprgrade de l'intégration Freebox dans HA https://github.com/home-assistant/core/pull/45837
Si c'est le cas on devrait pouvoir récupérer les capteurs du pack de sécurité dans HA. Je ne sait pas s'ils cherchent des testeurs pour valider ?

**Comment by SNoof85** [comment]
Ce PR est dans intégré dans la version dev de HA Core pas encore dans la version en production.
Et surtout il reste à faire le développement de la platform dans HA maintenant.

**Comment by floriant29** [comment]
Ok merci pour le retour !
